export enum IndicationEnum {
  USER_ABORTED = 'USER_ABORTED',
  NO_FINGER = 'NO_FINGER',
  MOVE_FINGER_UP = 'MOVE_FINGER_UP',
  MOVE_FINGER_DOWN = 'MOVE_FINGER_DOWN',
  MOVE_FINGER_LEFT = 'MOVE_FINGER_LEFT',
  MOVE_FINGER_RIGHT = 'MOVE_FINGER_RIGHT',
  PRESS_FINGER_HARDER = 'PRESS_FINGER_HARDER',
  LATENT_FINGER_DETECTED = 'LATENT_FINGER_DETECTED',
  REMOVE_FINGER = 'REMOVE_FINGER',
  FINGER_ACQUISITION_OK = 'FINGER_ACQUISITION_OK',
  FINGER_DETECTED = 'FINGER_DETECTED',
  FINGER_MISPLACED = 'FINGER_MISPLACED',
  FINGERPRINT_ACQUISITION_OK = 'FINGERPRINT_ACQUISITION_OK'
}