---
apiVersion: v1
data:
  env.js: |
    (function(window) {
    window["env"] = window["env"] || {};

    // Environment variables
    window["env"]["apiUrl"] = "{{(ds "properties").CONFIG.BACKENDURL }}";
    window["env"]["debug"] = true;
    window["env"]["cryptokey"] = "{{(ds "properties").CONFIG.CRYPTO_KEY }}";

    })(this);
kind: ConfigMap
metadata:
  name: {{ (ds "properties").APP_NAME }}-cm
  namespace: {{(ds "properties").NAMESPACE }}
